name: Node.js CI

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '12.x'
      - name: install dependencies
      - run: yarn
      - name: run ci script
      - run: yarn ci
      - name: run tests
      - run: yarn test
      - name: build application
      - run: yarn build